--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend.lua"
local CreatePositionFrame = luaExtend.CreatePositionFrame
local CreateVisibleFrame = luaExtend.CreateVisibleFrame
local CreateColorFrame = luaExtend.CreateColorFrame
local CreateEventFrame = luaExtend.CreateEventFrame
local CreateInnerActionFrame = luaExtend.CreateInnerActionFrame
local CreateAlphaFrame = luaExtend.CreateAlphaFrame
local CreateZOrderFrame = luaExtend.CreateZOrderFrame
local CreateScaleFrame = luaExtend.CreateScaleFrame
local CreateRotationSkewFrame = luaExtend.CreateRotationSkewFrame
local CreateAnchorPointFrame = luaExtend.CreateAnchorPointFrame
local CreateTextureFrame = luaExtend.CreateTextureFrame

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()  
Node:setName("Node")
Node:setPosition(0, 0)
Node:setScaleX(1)
Node:setScaleY(1)
Node:setLocalZOrder(0)
Node:setAnchorPoint(0, 0)
Node:setOpacity(255)
Node:setColor(cc.c3b(255, 255, 255))
Node:setVisible(true)
Node:setRotation(0)
Node:setRotationSkewX(0)
Node:setRotationSkewY(0)
Node:setTag(98)
Node:setCascadeColorEnabled(true)
Node:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Node)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(0)
layout:setRightMargin(0)
layout:setTopMargin(0)
layout:setBottomMargin(0)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("ui/common/mask_img.png",0)

Image_1:setFlippedX(false)
Image_1:setFlippedY(false)

Image_1:setScale9Enabled(true)
Image_1:setCapInsets(cc.rect(20,20,44,43))
Image_1:setTouchEnabled(true)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setPosition(0, 0)
Image_1:setScaleX(1)
Image_1:setScaleY(1)
Image_1:setLocalZOrder(0)
Image_1:setAnchorPoint(0.5, 0.5)
Image_1:setOpacity(255)
Image_1:setColor(cc.c3b(255, 255, 255))
Image_1:setVisible(true)
Image_1:setRotation(0)
Image_1:setRotationSkewX(0)
Image_1:setRotationSkewY(0)
Image_1:setTag(99)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(1350, 860))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-675)
layout:setRightMargin(-675)
layout:setTopMargin(-430)
layout:setBottomMargin(-430)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Image_1)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:setFontSize(36)
Text_1:setString([[健康游戏忠告]])
Text_1:setTextHorizontalAlignment(0)
Text_1:setTextVerticalAlignment(0)
Text_1:setTouchScaleChangeEnabled(false)
Text_1:setFlippedX(false)
Text_1:setFlippedY(false)
Text_1:setTouchEnabled(false)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setPosition(0.2133789, 145.4021)
Text_1:setScaleX(1)
Text_1:setScaleY(1)
Text_1:setLocalZOrder(0)
Text_1:setAnchorPoint(0.5, 0.5)
Text_1:setOpacity(255)
Text_1:setColor(cc.c3b(255, 255, 255))
Text_1:setVisible(true)
Text_1:setRotation(0)
Text_1:setRotationSkewX(0)
Text_1:setRotationSkewY(0)
Text_1:setTag(102)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(216, 36))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-107.7866)
layout:setRightMargin(-108.2134)
layout:setTopMargin(-163.4021)
layout:setBottomMargin(127.4021)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Text_1)

--Create Text_2
local Text_2 = ccui.Text:create()
Text_2:setFontSize(26)
Text_2:setString([[抵制不良游戏，拒绝盗版游戏]])
Text_2:setTextHorizontalAlignment(0)
Text_2:setTextVerticalAlignment(0)
Text_2:setTouchScaleChangeEnabled(false)
Text_2:setFlippedX(false)
Text_2:setFlippedY(false)
Text_2:setTouchEnabled(false)
Text_2:setLayoutComponentEnabled(true)
Text_2:setName("Text_2")
Text_2:setPosition(-2.121216, 82.40271)
Text_2:setScaleX(1)
Text_2:setScaleY(1)
Text_2:setLocalZOrder(0)
Text_2:setAnchorPoint(0.5, 0.5)
Text_2:setOpacity(255)
Text_2:setColor(cc.c3b(255, 255, 255))
Text_2:setVisible(true)
Text_2:setRotation(0)
Text_2:setRotationSkewX(0)
Text_2:setRotationSkewY(0)
Text_2:setTag(103)
Text_2:setCascadeColorEnabled(true)
Text_2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_2)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(338, 26))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-171.1212)
layout:setRightMargin(-166.8788)
layout:setTopMargin(-95.40271)
layout:setBottomMargin(69.40271)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Text_2)

--Create Text_3
local Text_3 = ccui.Text:create()
Text_3:setFontSize(26)
Text_3:setString([[注意自我保护，谨防受骗上当]])
Text_3:setTextHorizontalAlignment(0)
Text_3:setTextVerticalAlignment(0)
Text_3:setTouchScaleChangeEnabled(false)
Text_3:setFlippedX(false)
Text_3:setFlippedY(false)
Text_3:setTouchEnabled(false)
Text_3:setLayoutComponentEnabled(true)
Text_3:setName("Text_3")
Text_3:setPosition(-2.121216, 33.40271)
Text_3:setScaleX(1)
Text_3:setScaleY(1)
Text_3:setLocalZOrder(0)
Text_3:setAnchorPoint(0.5, 0.5)
Text_3:setOpacity(255)
Text_3:setColor(cc.c3b(255, 255, 255))
Text_3:setVisible(true)
Text_3:setRotation(0)
Text_3:setRotationSkewX(0)
Text_3:setRotationSkewY(0)
Text_3:setTag(104)
Text_3:setCascadeColorEnabled(true)
Text_3:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_3)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(338, 26))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-171.1212)
layout:setRightMargin(-166.8788)
layout:setTopMargin(-46.40271)
layout:setBottomMargin(20.40271)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Text_3)

--Create Text_4
local Text_4 = ccui.Text:create()
Text_4:setFontSize(26)
Text_4:setString([[适度游戏益脑，沉迷游戏伤身]])
Text_4:setTextHorizontalAlignment(0)
Text_4:setTextVerticalAlignment(0)
Text_4:setTouchScaleChangeEnabled(false)
Text_4:setFlippedX(false)
Text_4:setFlippedY(false)
Text_4:setTouchEnabled(false)
Text_4:setLayoutComponentEnabled(true)
Text_4:setName("Text_4")
Text_4:setPosition(-2.121216, -15.59729)
Text_4:setScaleX(1)
Text_4:setScaleY(1)
Text_4:setLocalZOrder(0)
Text_4:setAnchorPoint(0.5, 0.5)
Text_4:setOpacity(255)
Text_4:setColor(cc.c3b(255, 255, 255))
Text_4:setVisible(true)
Text_4:setRotation(0)
Text_4:setRotationSkewX(0)
Text_4:setRotationSkewY(0)
Text_4:setTag(105)
Text_4:setCascadeColorEnabled(true)
Text_4:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_4)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(338, 26))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-171.1212)
layout:setRightMargin(-166.8788)
layout:setTopMargin(2.59729)
layout:setBottomMargin(-28.59729)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Text_4)

--Create Text_5
local Text_5 = ccui.Text:create()
Text_5:setFontSize(26)
Text_5:setString([[合理安排时间，享受健康生活]])
Text_5:setTextHorizontalAlignment(0)
Text_5:setTextVerticalAlignment(0)
Text_5:setTouchScaleChangeEnabled(false)
Text_5:setFlippedX(false)
Text_5:setFlippedY(false)
Text_5:setTouchEnabled(false)
Text_5:setLayoutComponentEnabled(true)
Text_5:setName("Text_5")
Text_5:setPosition(-2.121216, -64.59731)
Text_5:setScaleX(1)
Text_5:setScaleY(1)
Text_5:setLocalZOrder(0)
Text_5:setAnchorPoint(0.5, 0.5)
Text_5:setOpacity(255)
Text_5:setColor(cc.c3b(255, 255, 255))
Text_5:setVisible(true)
Text_5:setRotation(0)
Text_5:setRotationSkewX(0)
Text_5:setRotationSkewY(0)
Text_5:setTag(106)
Text_5:setCascadeColorEnabled(true)
Text_5:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_5)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(338, 26))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-171.1212)
layout:setRightMargin(-166.8788)
layout:setTopMargin(51.59731)
layout:setBottomMargin(-77.59731)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Text_5)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

