--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend.lua"
local CreatePositionFrame = luaExtend.CreatePositionFrame
local CreateVisibleFrame = luaExtend.CreateVisibleFrame
local CreateColorFrame = luaExtend.CreateColorFrame
local CreateEventFrame = luaExtend.CreateEventFrame
local CreateInnerActionFrame = luaExtend.CreateInnerActionFrame
local CreateAlphaFrame = luaExtend.CreateAlphaFrame
local CreateZOrderFrame = luaExtend.CreateZOrderFrame
local CreateScaleFrame = luaExtend.CreateScaleFrame
local CreateRotationSkewFrame = luaExtend.CreateRotationSkewFrame
local CreateAnchorPointFrame = luaExtend.CreateAnchorPointFrame
local CreateTextureFrame = luaExtend.CreateTextureFrame

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()  
Node:setName("Node")
Node:setPosition(0, 0)
Node:setScaleX(1)
Node:setScaleY(1)
Node:setLocalZOrder(0)
Node:setAnchorPoint(0, 0)
Node:setOpacity(255)
Node:setColor(cc.c3b(255, 255, 255))
Node:setVisible(true)
Node:setRotation(0)
Node:setRotationSkewX(0)
Node:setRotationSkewY(0)
Node:setTag(69)
Node:setCascadeColorEnabled(true)
Node:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Node)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(0)
layout:setRightMargin(0)
layout:setTopMargin(0)
layout:setBottomMargin(0)

--Create panal
local panal = ccui.ImageView:create()
panal:ignoreContentAdaptWithSize(false)
panal:loadTexture("ui/common/mask_img.png",0)

panal:setFlippedX(false)
panal:setFlippedY(false)

panal:setScale9Enabled(true)
panal:setCapInsets(cc.rect(20,20,44,43))
panal:setTouchEnabled(true)
panal:setLayoutComponentEnabled(true)
panal:setName("panal")
panal:setPosition(0, 0)
panal:setScaleX(1)
panal:setScaleY(1)
panal:setLocalZOrder(0)
panal:setAnchorPoint(0.5, 0.5)
panal:setOpacity(255)
panal:setColor(cc.c3b(255, 255, 255))
panal:setVisible(true)
panal:setRotation(0)
panal:setRotationSkewX(0)
panal:setRotationSkewY(0)
panal:setTag(70)
panal:setCascadeColorEnabled(true)
panal:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panal)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(1350, 860))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-675)
layout:setRightMargin(-675)
layout:setTopMargin(-430)
layout:setBottomMargin(-430)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(panal)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("ui/informate/bg.png",0)

bg:setFlippedX(false)
bg:setFlippedY(false)

bg:setScale9Enabled(false)
bg:setCapInsets(cc.rect(0,0,1325,760))
bg:setTouchEnabled(false)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setPosition(0, 0)
bg:setScaleX(1)
bg:setScaleY(1)
bg:setLocalZOrder(0)
bg:setAnchorPoint(0.5, 0.5)
bg:setOpacity(255)
bg:setColor(cc.c3b(255, 255, 255))
bg:setVisible(true)
bg:setRotation(0)
bg:setRotationSkewX(0)
bg:setRotationSkewY(0)
bg:setTag(71)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(1325, 760))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-662.5)
layout:setRightMargin(-662.5)
layout:setTopMargin(-380)
layout:setBottomMargin(-380)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(bg)

--Create scrollView
local scrollView = ccui.ScrollView:create()

scrollView:setBounceEnabled(false)
scrollView:setDirection(1)
scrollView:setInnerContainerSize(cc.size(1054,920))

scrollView:ignoreContentAdaptWithSize(false)

scrollView:setClippingEnabled(true)
scrollView:setBackGroundImageCapInsets(cc.rect(0,0,0,0))
scrollView:setBackGroundColor(cc.c3b(255, 150, 100))
scrollView:setBackGroundColor(cc.c3b(255, 150, 100),cc.c3b(255, 255, 255))
scrollView:setBackGroundColorVector(cc.p(0,1))
scrollView:setBackGroundColorType(0)
scrollView:setBackGroundColorOpacity(102)
scrollView:setBackGroundImageScale9Enabled(false)

scrollView:setTouchEnabled(true)
scrollView:setLayoutComponentEnabled(true)
scrollView:setName("scrollView")
scrollView:setPosition(-524.5823, -306.3356)
scrollView:setScaleX(1)
scrollView:setScaleY(1)
scrollView:setLocalZOrder(0)
scrollView:setAnchorPoint(0, 0)
scrollView:setOpacity(255)
scrollView:setColor(cc.c3b(255, 255, 255))
scrollView:setVisible(true)
scrollView:setRotation(0)
scrollView:setRotationSkewX(0)
scrollView:setRotationSkewY(0)
scrollView:setTag(396)
scrollView:setCascadeColorEnabled(true)
scrollView:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(scrollView)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(1054, 460))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-524.5823)
layout:setRightMargin(-529.4177)
layout:setTopMargin(-153.6644)
layout:setBottomMargin(-306.3356)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(scrollView)

--Create topFrame
local topFrame = ccui.ImageView:create()
topFrame:ignoreContentAdaptWithSize(false)
topFrame:loadTexture("ui/informate/topFrame.png",0)

topFrame:setFlippedX(false)
topFrame:setFlippedY(false)

topFrame:setScale9Enabled(false)
topFrame:setCapInsets(cc.rect(0,0,1065,112))
topFrame:setTouchEnabled(false)
topFrame:setLayoutComponentEnabled(true)
topFrame:setName("topFrame")
topFrame:setPosition(0, 204.2846)
topFrame:setScaleX(1)
topFrame:setScaleY(1)
topFrame:setLocalZOrder(0)
topFrame:setAnchorPoint(0.5, 0.5)
topFrame:setOpacity(255)
topFrame:setColor(cc.c3b(255, 255, 255))
topFrame:setVisible(true)
topFrame:setRotation(0)
topFrame:setRotationSkewX(0)
topFrame:setRotationSkewY(0)
topFrame:setTag(72)
topFrame:setCascadeColorEnabled(true)
topFrame:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(topFrame)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(1065, 112))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-532.5)
layout:setRightMargin(-532.5)
layout:setTopMargin(-260.2846)
layout:setBottomMargin(148.2846)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(topFrame)

--Create closeBtn
local closeBtn = ccui.Button:create()
closeBtn:ignoreContentAdaptWithSize(false)
closeBtn:loadTextureNormal("ui/informate/close.png",0)
closeBtn:loadTexturePressed("ui/informate/closeOn.png",0)
closeBtn:loadTextureDisabled("Default/Button_Disable.png",0)
closeBtn:setTitleFontSize(14)
closeBtn:setTitleText("")
closeBtn:setTitleColor(cc.c3b(65, 65, 70))
closeBtn:setFlippedX(false)
closeBtn:setFlippedY(false)
closeBtn:setScale9Enabled(true)
closeBtn:setCapInsets(cc.rect(0,0,72,88))
closeBtn:setBright(true)
closeBtn:setTouchEnabled(true)
closeBtn:setLayoutComponentEnabled(true)
closeBtn:setName("closeBtn")
closeBtn:setPosition(596.4755, 327.8569)
closeBtn:setScaleX(1)
closeBtn:setScaleY(1)
closeBtn:setLocalZOrder(0)
closeBtn:setAnchorPoint(0.5, 0.5)
closeBtn:setOpacity(255)
closeBtn:setColor(cc.c3b(255, 255, 255))
closeBtn:setVisible(true)
closeBtn:setRotation(0)
closeBtn:setRotationSkewX(0)
closeBtn:setRotationSkewY(0)
closeBtn:setTag(73)
closeBtn:setCascadeColorEnabled(true)
closeBtn:setCascadeOpacityEnabled(true)
if callBackProvider~=nil then
      closeBtn:addClickEventListener(callBackProvider("InformateStudio.lua", closeBtn, "clickEvent"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(closeBtn)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(81, 94))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(555.9755)
layout:setRightMargin(-636.9755)
layout:setTopMargin(-374.8569)
layout:setBottomMargin(280.8569)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(closeBtn)

--Create title
local title = cc.Sprite:create("ui/informate/title_CN.png")
title:setName("title")
title:setPosition(0, 315.2445)
title:setScaleX(1)
title:setScaleY(1)
title:setLocalZOrder(0)
title:setAnchorPoint(0.5, 0.5)
title:setOpacity(255)
title:setColor(cc.c3b(255, 255, 255))
title:setVisible(true)
title:setRotation(0)
title:setRotationSkewX(0)
title:setRotationSkewY(0)
title:setTag(272)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(title)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(572, 68))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-286)
layout:setRightMargin(-286)
layout:setTopMargin(-349.2445)
layout:setBottomMargin(281.2445)
title:setFlippedX(false)
title:setFlippedY(false)
Node:addChild(title)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

