--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend.lua"
local CreatePositionFrame = luaExtend.CreatePositionFrame
local CreateVisibleFrame = luaExtend.CreateVisibleFrame
local CreateColorFrame = luaExtend.CreateColorFrame
local CreateEventFrame = luaExtend.CreateEventFrame
local CreateInnerActionFrame = luaExtend.CreateInnerActionFrame
local CreateAlphaFrame = luaExtend.CreateAlphaFrame
local CreateZOrderFrame = luaExtend.CreateZOrderFrame
local CreateScaleFrame = luaExtend.CreateScaleFrame
local CreateRotationSkewFrame = luaExtend.CreateRotationSkewFrame
local CreateAnchorPointFrame = luaExtend.CreateAnchorPointFrame
local CreateTextureFrame = luaExtend.CreateTextureFrame

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()  
Node:setName("Node")
Node:setPosition(0, 0)
Node:setScaleX(1)
Node:setScaleY(1)
Node:setLocalZOrder(0)
Node:setAnchorPoint(0, 0)
Node:setOpacity(255)
Node:setColor(cc.c3b(255, 255, 255))
Node:setVisible(true)
Node:setRotation(0)
Node:setRotationSkewX(0)
Node:setRotationSkewY(0)
Node:setTag(378)
Node:setCascadeColorEnabled(true)
Node:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Node)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(0)
layout:setRightMargin(0)
layout:setTopMargin(0)
layout:setBottomMargin(0)

--Create panel
local panel = ccui.ImageView:create()
panel:ignoreContentAdaptWithSize(false)
panel:loadTexture("ui/common/mask_img.png",0)

panel:setFlippedX(false)
panel:setFlippedY(false)

panel:setScale9Enabled(true)
panel:setCapInsets(cc.rect(20,20,44,43))
panel:setTouchEnabled(true)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setPosition(0, 0)
panel:setScaleX(1)
panel:setScaleY(1)
panel:setLocalZOrder(0)
panel:setAnchorPoint(0.5, 0.5)
panel:setOpacity(255)
panel:setColor(cc.c3b(255, 255, 255))
panel:setVisible(true)
panel:setRotation(0)
panel:setRotationSkewX(0)
panel:setRotationSkewY(0)
panel:setTag(379)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(1350, 860))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-675)
layout:setRightMargin(-675)
layout:setTopMargin(-430)
layout:setBottomMargin(-430)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(panel)

--Create heroIconBg_3
local heroIconBg_3 = cc.Sprite:create("ui/getHero/heroIconBg.png")
heroIconBg_3:setName("heroIconBg_3")
heroIconBg_3:setPosition(0, 153.7383)
heroIconBg_3:setScaleX(1)
heroIconBg_3:setScaleY(1)
heroIconBg_3:setLocalZOrder(0)
heroIconBg_3:setAnchorPoint(0.5, 0.5)
heroIconBg_3:setOpacity(255)
heroIconBg_3:setColor(cc.c3b(255, 255, 255))
heroIconBg_3:setVisible(true)
heroIconBg_3:setRotation(0)
heroIconBg_3:setRotationSkewX(0)
heroIconBg_3:setRotationSkewY(0)
heroIconBg_3:setTag(382)
heroIconBg_3:setCascadeColorEnabled(true)
heroIconBg_3:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(heroIconBg_3)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(288, 297))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-144)
layout:setRightMargin(-144)
layout:setTopMargin(-302.2383)
layout:setBottomMargin(5.238297)
heroIconBg_3:setFlippedX(false)
heroIconBg_3:setFlippedY(false)
Node:addChild(heroIconBg_3)

--Create ribbon_2
local ribbon_2 = cc.Sprite:create("ui/getHero/ribbon.png")
ribbon_2:setName("ribbon_2")
ribbon_2:setPosition(0, -9.6906)
ribbon_2:setScaleX(1)
ribbon_2:setScaleY(1)
ribbon_2:setLocalZOrder(0)
ribbon_2:setAnchorPoint(0.5, 0.5)
ribbon_2:setOpacity(255)
ribbon_2:setColor(cc.c3b(255, 255, 255))
ribbon_2:setVisible(true)
ribbon_2:setRotation(0)
ribbon_2:setRotationSkewX(0)
ribbon_2:setRotationSkewY(0)
ribbon_2:setTag(381)
ribbon_2:setCascadeColorEnabled(true)
ribbon_2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(ribbon_2)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(620, 133))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-310)
layout:setRightMargin(-310)
layout:setTopMargin(-56.8094)
layout:setBottomMargin(-76.1906)
ribbon_2:setFlippedX(false)
ribbon_2:setFlippedY(false)
Node:addChild(ribbon_2)

--Create heroNameImg
local heroNameImg = cc.Sprite:create("ui/hall/heroHome/heroName/110101_CN.png")
heroNameImg:setName("heroNameImg")
heroNameImg:setPosition(310.7139, 89.1669)
heroNameImg:setScaleX(1.25)
heroNameImg:setScaleY(1.25)
heroNameImg:setLocalZOrder(0)
heroNameImg:setAnchorPoint(0.5, 0.5)
heroNameImg:setOpacity(255)
heroNameImg:setColor(cc.c3b(255, 255, 255))
heroNameImg:setVisible(true)
heroNameImg:setRotation(0)
heroNameImg:setRotationSkewX(0)
heroNameImg:setRotationSkewY(0)
heroNameImg:setTag(384)
heroNameImg:setCascadeColorEnabled(true)
heroNameImg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(heroNameImg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5011514)
layout:setPositionPercentY(0.6704278)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(185, 33))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(218.2139)
layout:setRightMargin(216.7861)
layout:setTopMargin(27.3331)
layout:setBottomMargin(72.6669)
heroNameImg:setFlippedX(false)
heroNameImg:setFlippedY(false)
ribbon_2:addChild(heroNameImg)

--Create textImg_4
local textImg_4 = cc.Sprite:create("ui/getHero/textImg.png")
textImg_4:setName("textImg_4")
textImg_4:setPosition(0, -157.6902)
textImg_4:setScaleX(1)
textImg_4:setScaleY(1)
textImg_4:setLocalZOrder(0)
textImg_4:setAnchorPoint(0.5, 0.5)
textImg_4:setOpacity(255)
textImg_4:setColor(cc.c3b(255, 255, 255))
textImg_4:setVisible(true)
textImg_4:setRotation(0)
textImg_4:setRotationSkewX(0)
textImg_4:setRotationSkewY(0)
textImg_4:setTag(383)
textImg_4:setCascadeColorEnabled(true)
textImg_4:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(textImg_4)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(566, 125))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-283)
layout:setRightMargin(-283)
layout:setTopMargin(95.1902)
layout:setBottomMargin(-220.1902)
textImg_4:setFlippedX(false)
textImg_4:setFlippedY(false)
Node:addChild(textImg_4)

--Create continueLab
local continueLab = ccui.Text:create()
continueLab:setFontSize(26)
continueLab:setString([[点击继续]])
continueLab:setTextHorizontalAlignment(0)
continueLab:setTextVerticalAlignment(0)
continueLab:setTouchScaleChangeEnabled(false)
continueLab:setFlippedX(false)
continueLab:setFlippedY(false)
continueLab:setTouchEnabled(false)
continueLab:setLayoutComponentEnabled(true)
continueLab:setName("continueLab")
continueLab:setPosition(0.3209, -332.1072)
continueLab:setScaleX(1)
continueLab:setScaleY(1)
continueLab:setLocalZOrder(0)
continueLab:setAnchorPoint(0.5, 0.5)
continueLab:setOpacity(255)
continueLab:setColor(cc.c3b(252, 255, 0))
continueLab:setVisible(true)
continueLab:setRotation(0)
continueLab:setRotationSkewX(0)
continueLab:setRotationSkewY(0)
continueLab:setTag(386)
continueLab:setCascadeColorEnabled(true)
continueLab:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(continueLab)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(104, 26))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-51.6791)
layout:setRightMargin(-52.3209)
layout:setTopMargin(319.1072)
layout:setBottomMargin(-345.1072)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(continueLab)

--Create heroIcon
local heroIcon = cc.Sprite:create("ui/Icons/heroIcon/110101.png")
heroIcon:setName("heroIcon")
heroIcon:setPosition(1, 157.1428)
heroIcon:setScaleX(1.5)
heroIcon:setScaleY(1.5)
heroIcon:setLocalZOrder(0)
heroIcon:setAnchorPoint(0.5, 0.5)
heroIcon:setOpacity(255)
heroIcon:setColor(cc.c3b(255, 255, 255))
heroIcon:setVisible(true)
heroIcon:setRotation(0)
heroIcon:setRotationSkewX(0)
heroIcon:setRotationSkewY(0)
heroIcon:setTag(432)
heroIcon:setCascadeColorEnabled(true)
heroIcon:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(heroIcon)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(110, 110))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-54)
layout:setRightMargin(-56)
layout:setTopMargin(-212.1428)
layout:setBottomMargin(102.1428)
heroIcon:setFlippedX(false)
heroIcon:setFlippedY(false)
Node:addChild(heroIcon)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

