--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend.lua"
local CreatePositionFrame = luaExtend.CreatePositionFrame
local CreateVisibleFrame = luaExtend.CreateVisibleFrame
local CreateColorFrame = luaExtend.CreateColorFrame
local CreateEventFrame = luaExtend.CreateEventFrame
local CreateInnerActionFrame = luaExtend.CreateInnerActionFrame
local CreateAlphaFrame = luaExtend.CreateAlphaFrame
local CreateZOrderFrame = luaExtend.CreateZOrderFrame
local CreateScaleFrame = luaExtend.CreateScaleFrame
local CreateRotationSkewFrame = luaExtend.CreateRotationSkewFrame
local CreateAnchorPointFrame = luaExtend.CreateAnchorPointFrame
local CreateTextureFrame = luaExtend.CreateTextureFrame

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()  
Node:setName("Node")
Node:setPosition(0, 0)
Node:setScaleX(1)
Node:setScaleY(1)
Node:setLocalZOrder(0)
Node:setAnchorPoint(0, 0)
Node:setOpacity(255)
Node:setColor(cc.c3b(255, 255, 255))
Node:setVisible(true)
Node:setRotation(0)
Node:setRotationSkewX(0)
Node:setRotationSkewY(0)
Node:setTag(91)
Node:setCascadeColorEnabled(true)
Node:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Node)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(0)
layout:setRightMargin(0)
layout:setTopMargin(0)
layout:setBottomMargin(0)

--Create panel
local panel = ccui.ImageView:create()
panel:ignoreContentAdaptWithSize(false)
panel:loadTexture("ui/common/mask_img.png",0)

panel:setFlippedX(false)
panel:setFlippedY(false)

panel:setScale9Enabled(true)
panel:setCapInsets(cc.rect(20,20,44,43))
panel:setTouchEnabled(true)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setPosition(0, 0)
panel:setScaleX(1)
panel:setScaleY(1)
panel:setLocalZOrder(0)
panel:setAnchorPoint(0.5, 0.5)
panel:setOpacity(0)
panel:setColor(cc.c3b(255, 255, 255))
panel:setVisible(true)
panel:setRotation(0)
panel:setRotationSkewX(0)
panel:setRotationSkewY(0)
panel:setTag(92)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(1350, 860))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-675)
layout:setRightMargin(-675)
layout:setTopMargin(-430)
layout:setBottomMargin(-430)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(panel)

--Create okBtn
local okBtn = ccui.Button:create()
okBtn:ignoreContentAdaptWithSize(false)
okBtn:loadTextureNormal("ui/fight/gameGuide/btnOk_CN.png",0)
okBtn:loadTexturePressed("ui/fight/gameGuide/btnOk2_CN.png",0)
okBtn:loadTextureDisabled("Default/Button_Disable.png",0)
okBtn:setTitleFontSize(14)
okBtn:setTitleText("")
okBtn:setTitleColor(cc.c3b(65, 65, 70))
okBtn:setFlippedX(false)
okBtn:setFlippedY(false)
okBtn:setScale9Enabled(true)
okBtn:setCapInsets(cc.rect(0,0,366,95))
okBtn:setBright(true)
okBtn:setTouchEnabled(true)
okBtn:setLayoutComponentEnabled(true)
okBtn:setName("okBtn")
okBtn:setPosition(-0.2234, -270.7231)
okBtn:setScaleX(1)
okBtn:setScaleY(1)
okBtn:setLocalZOrder(0)
okBtn:setAnchorPoint(0.5, 0.5)
okBtn:setOpacity(255)
okBtn:setColor(cc.c3b(255, 255, 255))
okBtn:setVisible(true)
okBtn:setRotation(0)
okBtn:setRotationSkewX(0)
okBtn:setRotationSkewY(0)
okBtn:setTag(81)
okBtn:setCascadeColorEnabled(true)
okBtn:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(okBtn)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(366, 95))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-183.2234)
layout:setRightMargin(-182.7766)
layout:setTopMargin(223.2231)
layout:setBottomMargin(-318.2231)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(okBtn)

--Create tipsBg_1
local tipsBg_1 = cc.Sprite:create("ui/fight/gameGuide/tipsBg.png")
tipsBg_1:setName("tipsBg_1")
tipsBg_1:setPosition(-2, -5.5)
tipsBg_1:setScaleX(1)
tipsBg_1:setScaleY(1)
tipsBg_1:setLocalZOrder(0)
tipsBg_1:setAnchorPoint(0.5, 0.5)
tipsBg_1:setOpacity(255)
tipsBg_1:setColor(cc.c3b(255, 255, 255))
tipsBg_1:setVisible(true)
tipsBg_1:setRotation(0)
tipsBg_1:setRotationSkewX(0)
tipsBg_1:setRotationSkewY(0)
tipsBg_1:setTag(93)
tipsBg_1:setCascadeColorEnabled(true)
tipsBg_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(tipsBg_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(799, 480))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-401.5)
layout:setRightMargin(-397.5)
layout:setTopMargin(-234.5)
layout:setBottomMargin(-245.5)
tipsBg_1:setFlippedX(false)
tipsBg_1:setFlippedY(false)
Node:addChild(tipsBg_1)

--Create content_1
local content_1 = cc.Sprite:create("ui/openMode/content.png")
content_1:setName("content_1")
content_1:setPosition(0, 0)
content_1:setScaleX(1)
content_1:setScaleY(1)
content_1:setLocalZOrder(0)
content_1:setAnchorPoint(0.5, 0.5)
content_1:setOpacity(255)
content_1:setColor(cc.c3b(255, 255, 255))
content_1:setVisible(true)
content_1:setRotation(0)
content_1:setRotationSkewX(0)
content_1:setRotationSkewY(0)
content_1:setTag(79)
content_1:setCascadeColorEnabled(true)
content_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(content_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(735, 323))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-367.5)
layout:setRightMargin(-367.5)
layout:setTopMargin(-161.5)
layout:setBottomMargin(-161.5)
content_1:setFlippedX(false)
content_1:setFlippedY(false)
Node:addChild(content_1)

--Create title_2
local title_2 = cc.Sprite:create("ui/openMode/title.png")
title_2:setName("title_2")
title_2:setPosition(0, 229.5)
title_2:setScaleX(1)
title_2:setScaleY(1)
title_2:setLocalZOrder(0)
title_2:setAnchorPoint(0.5, 0.5)
title_2:setOpacity(255)
title_2:setColor(cc.c3b(255, 255, 255))
title_2:setVisible(true)
title_2:setRotation(0)
title_2:setRotationSkewX(0)
title_2:setRotationSkewY(0)
title_2:setTag(80)
title_2:setCascadeColorEnabled(true)
title_2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(title_2)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(269, 62))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-134.5)
layout:setRightMargin(-134.5)
layout:setTopMargin(-260.5)
layout:setBottomMargin(198.5)
title_2:setFlippedX(false)
title_2:setFlippedY(false)
Node:addChild(title_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

