--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend.lua"
local CreatePositionFrame = luaExtend.CreatePositionFrame
local CreateVisibleFrame = luaExtend.CreateVisibleFrame
local CreateColorFrame = luaExtend.CreateColorFrame
local CreateEventFrame = luaExtend.CreateEventFrame
local CreateInnerActionFrame = luaExtend.CreateInnerActionFrame
local CreateAlphaFrame = luaExtend.CreateAlphaFrame
local CreateZOrderFrame = luaExtend.CreateZOrderFrame
local CreateScaleFrame = luaExtend.CreateScaleFrame
local CreateRotationSkewFrame = luaExtend.CreateRotationSkewFrame
local CreateAnchorPointFrame = luaExtend.CreateAnchorPointFrame
local CreateTextureFrame = luaExtend.CreateTextureFrame

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()  
Node:setName("Node")
Node:setPosition(0, 0)
Node:setScaleX(1)
Node:setScaleY(1)
Node:setLocalZOrder(0)
Node:setAnchorPoint(0, 0)
Node:setOpacity(255)
Node:setColor(cc.c3b(255, 255, 255))
Node:setVisible(true)
Node:setRotation(0)
Node:setRotationSkewX(0)
Node:setRotationSkewY(0)
Node:setTag(71)
Node:setCascadeColorEnabled(true)
Node:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Node)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(0)
layout:setRightMargin(0)
layout:setTopMargin(0)
layout:setBottomMargin(0)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("ui/opacity.png",0)
Button_1:loadTexturePressed("ui/opacity.png",0)
Button_1:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleText("Button")
Button_1:setTitleColor(cc.c3b(65, 65, 70))
Button_1:setFlippedX(false)
Button_1:setFlippedY(false)
Button_1:setScale9Enabled(true)
Button_1:setCapInsets(cc.rect(0,0,66,66))
Button_1:setBright(true)
Button_1:setTouchEnabled(true)
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setPosition(0, 0)
Button_1:setScaleX(1)
Button_1:setScaleY(1)
Button_1:setLocalZOrder(0)
Button_1:setAnchorPoint(0.5, 0.5)
Button_1:setOpacity(255)
Button_1:setColor(cc.c3b(255, 255, 255))
Button_1:setVisible(true)
Button_1:setRotation(0)
Button_1:setRotationSkewX(0)
Button_1:setRotationSkewY(0)
Button_1:setTag(73)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(1)
layout:setPercentHeight(1)
layout:setSize(cc.size(1350, 860))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-675)
layout:setRightMargin(-675)
layout:setTopMargin(-430)
layout:setBottomMargin(-430)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Button_1)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("ui/hall/JibanDetail/rightBg.png",0)

Image_1:setFlippedX(false)
Image_1:setFlippedY(false)

Image_1:setScale9Enabled(true)
Image_1:setCapInsets(cc.rect(10,10,80,80))
Image_1:setTouchEnabled(false)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setPosition(0, 0)
Image_1:setScaleX(1)
Image_1:setScaleY(1)
Image_1:setLocalZOrder(0)
Image_1:setAnchorPoint(0.5, 0.5)
Image_1:setOpacity(255)
Image_1:setColor(cc.c3b(255, 255, 255))
Image_1:setVisible(true)
Image_1:setRotation(0)
Image_1:setRotationSkewX(0)
Image_1:setRotationSkewY(0)
Image_1:setTag(74)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(1180, 680))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-590)
layout:setRightMargin(-590)
layout:setTopMargin(-340)
layout:setBottomMargin(-340)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Image_1)

--Create txt1
local txt1 = ccui.Text:create()
txt1:setFontSize(36)
txt1:setString([[第一行文字第一行文字第一行文字第一行文字]])
txt1:setTextHorizontalAlignment(0)
txt1:setTextVerticalAlignment(0)
txt1:setTouchScaleChangeEnabled(false)
txt1:setFlippedX(false)
txt1:setFlippedY(false)
txt1:setTouchEnabled(false)
txt1:setLayoutComponentEnabled(true)
txt1:setName("txt1")
txt1:setPosition(-360.5034, 201.1656)
txt1:setScaleX(1)
txt1:setScaleY(1)
txt1:setLocalZOrder(0)
txt1:setAnchorPoint(0, 0.5)
txt1:setOpacity(255)
txt1:setColor(cc.c3b(255, 255, 255))
txt1:setVisible(true)
txt1:setRotation(0)
txt1:setRotationSkewX(0)
txt1:setRotationSkewY(0)
txt1:setTag(75)
txt1:setCascadeColorEnabled(true)
txt1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(txt1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(720, 36))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-360.5034)
layout:setRightMargin(-359.4966)
layout:setTopMargin(-219.1656)
layout:setBottomMargin(183.1656)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(txt1)

--Create txt2
local txt2 = ccui.Text:create()
txt2:setFontSize(36)
txt2:setString([[第一行文字第一行文字第一行文字第一行文字]])
txt2:setTextHorizontalAlignment(0)
txt2:setTextVerticalAlignment(0)
txt2:setTouchScaleChangeEnabled(false)
txt2:setFlippedX(false)
txt2:setFlippedY(false)
txt2:setTouchEnabled(false)
txt2:setLayoutComponentEnabled(true)
txt2:setName("txt2")
txt2:setPosition(-360.5034, 120.1658)
txt2:setScaleX(1)
txt2:setScaleY(1)
txt2:setLocalZOrder(0)
txt2:setAnchorPoint(0, 0.5)
txt2:setOpacity(255)
txt2:setColor(cc.c3b(255, 255, 255))
txt2:setVisible(true)
txt2:setRotation(0)
txt2:setRotationSkewX(0)
txt2:setRotationSkewY(0)
txt2:setTag(76)
txt2:setCascadeColorEnabled(true)
txt2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(txt2)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(720, 36))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-360.5034)
layout:setRightMargin(-359.4966)
layout:setTopMargin(-138.1658)
layout:setBottomMargin(102.1658)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(txt2)

--Create txt3
local txt3 = ccui.Text:create()
txt3:setFontSize(36)
txt3:setString([[第一行文字第一行文字第一行文字第一行文字]])
txt3:setTextHorizontalAlignment(0)
txt3:setTextVerticalAlignment(0)
txt3:setTouchScaleChangeEnabled(false)
txt3:setFlippedX(false)
txt3:setFlippedY(false)
txt3:setTouchEnabled(false)
txt3:setLayoutComponentEnabled(true)
txt3:setName("txt3")
txt3:setPosition(-360.5034, 39.16656)
txt3:setScaleX(1)
txt3:setScaleY(1)
txt3:setLocalZOrder(0)
txt3:setAnchorPoint(0, 0.5)
txt3:setOpacity(255)
txt3:setColor(cc.c3b(255, 255, 255))
txt3:setVisible(true)
txt3:setRotation(0)
txt3:setRotationSkewX(0)
txt3:setRotationSkewY(0)
txt3:setTag(77)
txt3:setCascadeColorEnabled(true)
txt3:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(txt3)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(720, 36))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-360.5034)
layout:setRightMargin(-359.4966)
layout:setTopMargin(-57.16656)
layout:setBottomMargin(21.16656)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(txt3)

--Create txt4
local txt4 = ccui.Text:create()
txt4:setFontSize(36)
txt4:setString([[第一行文字第一行文字第一行文字第一行文字]])
txt4:setTextHorizontalAlignment(0)
txt4:setTextVerticalAlignment(0)
txt4:setTouchScaleChangeEnabled(false)
txt4:setFlippedX(false)
txt4:setFlippedY(false)
txt4:setTouchEnabled(false)
txt4:setLayoutComponentEnabled(true)
txt4:setName("txt4")
txt4:setPosition(-360.5034, -41.83289)
txt4:setScaleX(1)
txt4:setScaleY(1)
txt4:setLocalZOrder(0)
txt4:setAnchorPoint(0, 0.5)
txt4:setOpacity(255)
txt4:setColor(cc.c3b(255, 255, 255))
txt4:setVisible(true)
txt4:setRotation(0)
txt4:setRotationSkewX(0)
txt4:setRotationSkewY(0)
txt4:setTag(78)
txt4:setCascadeColorEnabled(true)
txt4:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(txt4)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(720, 36))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-360.5034)
layout:setRightMargin(-359.4966)
layout:setTopMargin(23.83289)
layout:setBottomMargin(-59.83289)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(txt4)

--Create txt5
local txt5 = ccui.Text:create()
txt5:setFontSize(36)
txt5:setString([[第一行文字第一行文字第一行文字第一行文字]])
txt5:setTextHorizontalAlignment(0)
txt5:setTextVerticalAlignment(0)
txt5:setTouchScaleChangeEnabled(false)
txt5:setFlippedX(false)
txt5:setFlippedY(false)
txt5:setTouchEnabled(false)
txt5:setLayoutComponentEnabled(true)
txt5:setName("txt5")
txt5:setPosition(-360.5034, -122.8339)
txt5:setScaleX(1)
txt5:setScaleY(1)
txt5:setLocalZOrder(0)
txt5:setAnchorPoint(0, 0.5)
txt5:setOpacity(255)
txt5:setColor(cc.c3b(255, 255, 255))
txt5:setVisible(true)
txt5:setRotation(0)
txt5:setRotationSkewX(0)
txt5:setRotationSkewY(0)
txt5:setTag(79)
txt5:setCascadeColorEnabled(true)
txt5:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(txt5)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(720, 36))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-360.5034)
layout:setRightMargin(-359.4966)
layout:setTopMargin(104.8339)
layout:setBottomMargin(-140.8339)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(txt5)

--Create txt6
local txt6 = ccui.Text:create()
txt6:setFontSize(36)
txt6:setString([[第一行文字第一行文字第一行文字第一行文字]])
txt6:setTextHorizontalAlignment(0)
txt6:setTextVerticalAlignment(0)
txt6:setTouchScaleChangeEnabled(false)
txt6:setFlippedX(false)
txt6:setFlippedY(false)
txt6:setTouchEnabled(false)
txt6:setLayoutComponentEnabled(true)
txt6:setName("txt6")
txt6:setPosition(-360.5034, -203.8339)
txt6:setScaleX(1)
txt6:setScaleY(1)
txt6:setLocalZOrder(0)
txt6:setAnchorPoint(0, 0.5)
txt6:setOpacity(255)
txt6:setColor(cc.c3b(255, 255, 255))
txt6:setVisible(true)
txt6:setRotation(0)
txt6:setRotationSkewX(0)
txt6:setRotationSkewY(0)
txt6:setTag(80)
txt6:setCascadeColorEnabled(true)
txt6:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(txt6)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)

layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)

layout:setPercentWidth(0)
layout:setPercentHeight(0)
layout:setSize(cc.size(720, 36))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-360.5034)
layout:setRightMargin(-359.4966)
layout:setTopMargin(185.8339)
layout:setBottomMargin(-221.8339)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(txt6)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

